In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('heart.csv')
data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

# Cheaking for Null Values

In [3]:
data.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

# Encoding The Catogorical Values

In [4]:
encoder  = LabelEncoder()
data['Sex'] = encoder.fit_transform(data['Sex'])
data['ChestPainType'] = encoder.fit_transform(data['ChestPainType'])
data['RestingECG'] = encoder.fit_transform(data['RestingECG'])
data['ST_Slope'] = encoder.fit_transform(data['ST_Slope'])
data['HeartDisease'] = encoder.fit_transform(data['HeartDisease'])
data['ExerciseAngina'] = encoder.fit_transform(data['ExerciseAngina'])

In [5]:
data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [6]:
data.to_csv('edited.csv')

In [7]:
x = data.drop('HeartDisease',axis=1)
y = data.drop(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope'], axis=1)

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [18]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [19]:
x_test

array([[ 0.18104948,  0.50771021, -0.83255771, ..., -0.83341543,
        -0.86584957, -0.60141349],
       [ 0.49613052,  0.50771021,  0.2088963 , ..., -0.83341543,
        -0.86584957,  1.05367644],
       [ 0.07602246,  0.50771021, -0.83255771, ...,  1.19988179,
         0.07330305, -0.60141349],
       ...,
       [ 0.60115754,  0.50771021, -0.83255771, ..., -0.83341543,
        -0.86584957,  1.05367644],
       [-0.55413963,  0.50771021, -0.83255771, ..., -0.83341543,
        -0.39627326, -0.60141349],
       [ 0.91623858, -1.96962753,  2.29180432, ..., -0.83341543,
        -0.86584957, -0.60141349]])

In [20]:
model = SVC()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

C:\Users\revan\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [22]:
from sklearn.metrics import accuracy_score

a = accuracy_score(y_test,y_pred)

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1], dtype=int64)

In [41]:
data.loc[:1:2]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0

In [17]:
dat['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [18]:
data['ST_Slope'].unique()

array([2, 1, 0])

In [12]:
dat.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [1]:
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QDialog
from PyQt5.QtWidgets import QApplication
from PyQt5.uic import loadUi
import sys

x = []

class page1(QDialog):
    def __init__(self):
        super(page1,self).__init__()
        loadUi('1.ui',self)
        self.next1.clicked.connect(self.p1)
        
    def p1(self):
        x.append(int(self.age.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
        
class page2(QDialog):
    def __init__(self):
        super(page2,self).__init__()
        loadUi('2.ui',self)
        self.next2.clicked.connect(self.p2)
        self.back2.clicked.connect(self.b2)
        
    def p2(self):
        x.append(int(self.gender.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b2(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page3(QDialog):
    def __init__(self):
        super(page3,self).__init__()
        loadUi('3.ui',self)
        self.next3.clicked.connect(self.p3)
        self.back3.clicked.connect(self.b3)
        
    def p3(self):
        x.append(int(self.chestpain.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b3(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page4(QDialog):
    def __init__(self):
        super(page4,self).__init__()
        loadUi('4.ui',self)
        self.next4.clicked.connect(self.p4)
        self.back4.clicked.connect(self.b4)
        
    def p4(self):
        x.append(int(self.rb.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b4(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page5(QDialog):
    def __init__(self):
        super(page5,self).__init__()
        loadUi('5.ui',self)
        self.next5.clicked.connect(self.p5)
        self.back5.clicked.connect(self.b5)
        
    def p5(self):
        x.append(int(self.Cholesterol.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b5(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page6(QDialog):
    def __init__(self):
        super(page6,self).__init__()
        loadUi('6.ui',self)
        self.next6.clicked.connect(self.p6)
        self.back6.clicked.connect(self.b6)
        
    def p6(self):
        x.append(int(self.fast.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b6(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page7(QDialog):
    def __init__(self):
        super(page7,self).__init__()
        loadUi('7.ui',self)
        self.next7.clicked.connect(self.p7)
        self.back7.clicked.connect(self.b7)
        
    def p7(self):
        x.append(int(self.recg.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b7(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page8(QDialog):
    def __init__(self):
        super(page8,self).__init__()
        loadUi('8.ui',self)
        self.next8.clicked.connect(self.p8)
        self.back8.clicked.connect(self.b8)
        
    def p8(self):
        x.append(int(self.mhr.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b8(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page9(QDialog):
    def __init__(self):
        super(page9,self).__init__()
        loadUi('9.ui',self)
        self.next9.clicked.connect(self.p9)
        self.back9.clicked.connect(self.b9)
        
    def p9(self):
        x.append(int(self.ea.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b9(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page10(QDialog):
    def __init__(self):
        super(page10,self).__init__()
        loadUi('10.ui',self)
        self.next10.clicked.connect(self.p10)
        self.back10.clicked.connect(self.b10)
        
    def p10(self):
        x.append(float(self.oldpeak.text()))
        widget.setCurrentIndex(widget.currentIndex()+1)
        
    def b10(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
        
class page11(QDialog):
    def __init__(self):
        super(page11,self).__init__()
        loadUi('11.ui',self)
        self.predict.clicked.connect(self.p11)
        self.back11.clicked.connect(self.b11)
        self.n.clicked.connect(self.new)
    def p11(self):
        global x
        x.append(int(self.st_slope.text()))
        
        import pandas as pd
        from sklearn.model_selection import train_test_split
        from sklearn.svm import SVC
        from sklearn.preprocessing import StandardScaler
        
        data = pd.read_csv('edited.csv')
        x1 = data.drop(['HeartDisease','Unnamed: 0'],axis=1)
        y = data.drop(['Unnamed: 0','Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
                       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope'], axis=1)
        x_train,x_test,y_train,y_test = train_test_split(x1,y)
        scaler = StandardScaler()
        x_train = scaler.fit_transform(x_train)
        x_test = scaler.transform(x_test)
        model = SVC()
        model.fit(x_train,y_train)
        x2 = scaler.transform([x])
        y_pred = model.predict(x2)
        if y_pred == 0:
            s = 'patient as no heart Diseases'
            self.result.setText(s)
        else:
            s = 'patient as heart Diseases'
            self.result.setText(s)
        
        
        
    def b11(self):
        x.pop()
        widget.setCurrentIndex(widget.currentIndex()-1)
        
    def new(self):
        x.clear()
        widget.setCurrentIndex(widget.currentIndex()-10)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    widget = QtWidgets.QStackedWidget()
    page1 = page1()
    page2 = page2()
    page3 = page3()
    page4 = page4()
    page5 = page5()
    page6 = page6()
    page7 = page7()
    page8 = page8()
    page9 = page9()
    page10 = page10()
    page11 = page11()
    widget.addWidget(page1)
    widget.addWidget(page2)
    widget.addWidget(page3)
    widget.addWidget(page4)
    widget.addWidget(page5)
    widget.addWidget(page6)
    widget.addWidget(page7)
    widget.addWidget(page8)
    widget.addWidget(page9)
    widget.addWidget(page10)
    widget.addWidget(page11)
    widget.setFixedHeight(422)
    widget.setFixedWidth(495)
    widget.show()
    sys.exit(app.exec_())

C:\Users\revan\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\revan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

SystemExit: 0

C:\Users\revan\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [2]:
data.head()

NameError: name 'data' is not defined